/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author win10
 */
public class SmallMargherita extends javax.swing.JFrame implements Pizza, Cheese{

    /**
     * Creates new form SmallMargherita
     */
    public SmallMargherita() {
        initComponents();
    }
    
    @Override
    public float checkCrust() {
        if (Thin.isSelected()) {
            return 20;
        }
        else {
            return 25;
        }
    }
    
    @Override
    public float hasVegetable() {
        return -1;
    }
    
    public float hasCheese(Cheese c) {
        
        float cheeseValue = 0;
        if (CheeseSelector.getSelectedIndex() == 0) {
            cheeseValue = c.Mozzarella();
        }
        else if (CheeseSelector.getSelectedIndex() == 1) {
            cheeseValue = c.Cheddar();
        }
        else if (CheeseSelector.getSelectedIndex() == 2) {
            cheeseValue = c.DoubleLayerMozzarella();
        }
        else if (CheeseSelector.getSelectedIndex() == 3) {
            cheeseValue = c.DoubleLayerCheddar();
        }
        else {
            cheeseValue = c.Mozzarella();
        }
        return cheeseValue;
    }
    
    @Override
    public float hasTopping() {
        if (Jalapino.isSelected()) {
            return 10;
        }
        else {
            return 12;
        }
    }
    
    @Override
    public String cookongTime() {
        return "20 minutes";
    }
    
    @Override
    public float totalCost() {
        float total;
        Cheese c = new Cheese() {
        @Override
        public float Mozzarella() {
            return 20;
        }

        @Override
        public float Cheddar() {
            return 25;
        }

        @Override
        public float DoubleLayerMozzarella() {
            return 25;
        }

        @Override
        public float DoubleLayerCheddar() {
            return 30;
        }
        };
        total = checkCrust() + hasCheese(c) + hasTopping() + 20;
        return total;
    }
    
    // Cheese Interface methods
    @Override
    public float Mozzarella() {
        return 20;
    }

    @Override
    public float Cheddar() {
        return 25;
    }

    @Override
    public float DoubleLayerMozzarella() {
        return 25;
    }

    @Override
    public float DoubleLayerCheddar() {
        return 30;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ToppingsAmt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Thin = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        Thick = new javax.swing.JRadioButton();
        BlackOlives = new javax.swing.JCheckBox();
        Jalapino = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        CheeseSelector = new javax.swing.JComboBox<>();
        MargheritaBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 176, 87));
        jLabel2.setText("Margherita");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 130, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        Amount.setEditable(false);
        Amount.setBackground(new java.awt.Color(240, 240, 240));
        Amount.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Amount.setForeground(new java.awt.Color(255, 255, 255));
        Amount.setEnabled(false);
        Amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountActionPerformed(evt);
            }
        });
        getContentPane().add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 60, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Toppings");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        ToppingsAmt.setEditable(false);
        ToppingsAmt.setBackground(new java.awt.Color(240, 240, 240));
        ToppingsAmt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ToppingsAmt.setForeground(new java.awt.Color(255, 255, 255));
        ToppingsAmt.setEnabled(false);
        ToppingsAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToppingsAmtActionPerformed(evt);
            }
        });
        getContentPane().add(ToppingsAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 60, 20));

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 150));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cheese");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        buttonGroup1.add(Thin);
        Thin.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Thin.setForeground(new java.awt.Color(255, 255, 255));
        Thin.setText("Thin");
        Thin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThinActionPerformed(evt);
            }
        });
        jPanel1.add(Thin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CRUST");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        buttonGroup1.add(Thick);
        Thick.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Thick.setForeground(new java.awt.Color(255, 255, 255));
        Thick.setText("Thick");
        Thick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThickActionPerformed(evt);
            }
        });
        jPanel1.add(Thick, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        BlackOlives.setForeground(new java.awt.Color(255, 255, 255));
        BlackOlives.setText("Black Olives");
        BlackOlives.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackOlivesActionPerformed(evt);
            }
        });
        jPanel1.add(BlackOlives, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        Jalapino.setForeground(new java.awt.Color(255, 255, 255));
        Jalapino.setText("Jalapino");
        Jalapino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JalapinoActionPerformed(evt);
            }
        });
        jPanel1.add(Jalapino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOPPINGS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        CheeseSelector.setForeground(new java.awt.Color(255, 255, 255));
        CheeseSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mozzarella", "Cheddar", "DoubleLayeredMozzarella", "DoubleLayeredCheddar" }));
        CheeseSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheeseSelectorActionPerformed(evt);
            }
        });
        jPanel1.add(CheeseSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 170, 200));

        MargheritaBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\win10\\Downloads\\depositphotos_292635914-stock-photo-pizza-cutting-board-at-wooden.jpg")); // NOI18N
        getContentPane().add(MargheritaBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThinActionPerformed

    private void ThickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThickActionPerformed

    private void BlackOlivesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackOlivesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BlackOlivesActionPerformed

    private void JalapinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JalapinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JalapinoActionPerformed

    private void CheeseSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheeseSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheeseSelectorActionPerformed

    private void AmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountActionPerformed

    private void ToppingsAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToppingsAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToppingsAmtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Calculate Cost:
        ToppingsAmt.setText("" + hasTopping());
        Amount.setText("" + totalCost());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmallMargherita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmallMargherita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmallMargherita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmallMargherita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmallMargherita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Amount;
    private javax.swing.JCheckBox BlackOlives;
    private javax.swing.JComboBox<String> CheeseSelector;
    private javax.swing.JCheckBox Jalapino;
    private javax.swing.JLabel MargheritaBackground;
    private javax.swing.JRadioButton Thick;
    private javax.swing.JRadioButton Thin;
    private javax.swing.JTextField ToppingsAmt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
